language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
before_deploy:
- zip -r mjfood *
- mkdir -p deploy
- mv mjfood.zip deploy/mjfood.zip
#  - mkdir -p before-deploy
#  - cp scripts/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
#  - cd before-deploy && zip -r before-deploy *
#  - cd ../ && mkdir -p deploy
#  - mv before-deploy/before-deploy.zip deploy/mjfood.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: mjfood-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: mjfood-build
  key: mjfood.zip
  bundle_type: zip
  application: mjfood
  deployment_group: mjfood-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    all_branches: true
  notifications:
    email:
      recipients:
      - kst20026@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv
  -in ./src/main/resources/application.yml.enc -out ./src/main/resources/application.yml -d
- openssl aes-256-cbc -K $encrypted_2e8be43b8f53_key -iv $encrypted_2e8be43b8f53_iv
  -in ./src/main/resources/application-oauth.yml.enc -out ./src/main/resources/application-oauth.yml
  -d
- openssl aes-256-cbc -K $encrypted_f728702889c9_key -iv $encrypted_f728702889c9_iv
  -in ./src/main/java/mj/mjfood/config/secret/Secret.java.enc -out ./src/main/java/mj/mjfood/config/secret/Secret.java
  -d
