spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 827052985059-35bracmr4mr01vrrd5olqaf0nrvmq1kh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://prod.kaydenserver.shop/{action}/oauth2/code/{registrationId}"
            scope: profile,email
          naver:
            client-id: kHM0xB5DImn6ULK7AbRs
            client-secret: VLytBnJCGT
            redirect-uri: "https://prod.kaydenserver.shop/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: 4a52b4d07fa05c6973ec76f1ec51fca7
            redirect-uri: "https://prod.kaydenserver.shop/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id